- notebooks/01_tabular_data_exploration.ipynb
- notebooks/02_basic_preprocessing_exercise_01.ipynb
- notebooks/02_basic_preprocessing_exercise_01_solution.ipynb
- notebooks/03_basic_preprocessing_categorical_variables_exercise_01.ipynb
- notebooks/03_basic_preprocessing_categorical_variables_exercise_01_solution.ipynb
- notebooks/03_basic_preprocessing_categorical_variables_exercise_02.ipynb
- notebooks/03_basic_preprocessing_categorical_variables_exercise_02_solution.ipynb
- python_scripts/01_tabular_data_exploration.py
- python_scripts/02_basic_preprocessing_exercise_01.py
- python_scripts/02_basic_preprocessing_exercise_01_solution.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_01.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_01_solution.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_02.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_02_solution.py
- rendered_notebooks/02_basic_preprocessing_exercise_01.ipynb
- rendered_notebooks/02_basic_preprocessing_exercise_01_solution.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables_exercise_01.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables_exercise_01_solution.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables_exercise_02.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables_exercise_02_solution.ipynb
Remove a few lines of that are not strictly necessary, partly does to improvements in the underlying libraries
> Simplify notebooks

- python_scripts/02_basic_preprocessing.py
- python_scripts/03_basic_preprocessing_categorical_variables.py
- python_scripts/04_basic_parameters_tuning.py
Fix #20 
Address minor typo in notebook 4
> Use make_column_selector to select numeric and categorical variables

- python_scripts/ensemble.py
Add a notebook to present the principle of bagging and additional randomization to have random-forest.
Add a presentation of the gradient-boosting.
Add a section regarding the important parameter and expected values of the random forest and gradient boosting.
> ENH add ensemble notebook

- python_scripts/02_basic_preprocessing.py
- python_scripts/02_basic_preprocessing_exercise_01.py
- python_scripts/02_basic_preprocessing_exercise_01_solution.py
- rendered_notebooks/02_basic_preprocessing.ipynb
- rendered_notebooks/02_basic_preprocessing_exercise_01.ipynb
- rendered_notebooks/02_basic_preprocessing_exercise_01_solution.ipynb
`cross_val_score` is introduced later in the notebook.
> Use train_test_split in exercise.

- python_scripts/04_basic_parameters_tuning.py
- rendered_notebooks/04_basic_parameters_tuning.ipynb
* From the text around it I think the goal was to first create a model with default parameters and say that there are no reason that these parameters are optional so I reverted to that.
* Shorten long markdown lines
> Tweaks to parameter tuning notebook.

- python_scripts/03_basic_preprocessing_categorical_variables.py
This feature was introduced recently (0.23) and is a nice addition
for a newcomer to visualise the content of the current pipeline.
@lesteve @jeremiedbb
> Add interactive view for pipelines

- python_scripts/02_basic_preprocessing.py
The text mentions both the scaling and the creation of the pipeline, which is two different informations in one go and only comes later in the code. 
This PR aims at splitting the text so the flow is improved.
@lesteve @jeremiedbb
> Reorder text to match code inputs

- python_scripts/02_basic_preprocessing.py
- python_scripts/03_basic_preprocessing_categorical_variables.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_01_solution.py
- rendered_notebooks/02_basic_preprocessing.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables.ipynb
- rendered_notebooks/03_basic_preprocessing_categorical_variables_exercise_01_solution.ipynb
This was to avoid a warning about default change in 0.21. The solver is lbfgs by default since 0.22
> Remove solver=lbfgs.

- .binder/environment.yml
- README.md
- environment.yml
- python_scripts/01_tabular_data_exploration.py
- requirements.txt
> Remove pandas-profiling

- jupyter-book/_toc.yml
- put intro notebooks into a single chapter "The predictive modeling pipeline".
- put ensemble models in same part as trees
> Improve structure of JupyterBook table of contents.

- python_scripts/trees.py
Removing the narration linked to the internal split mechanism.
I added a couple of insights regarding the prediction.
> ENH simplify the tree narration removing entropy explanation

- python_scripts/02_basic_preprocessing.py
- python_scripts/02_basic_preprocessing_exercise_01.py
- python_scripts/02_basic_preprocessing_exercise_01_solution.py
- python_scripts/03_basic_preprocessing_categorical_variables.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_01.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_01_solution.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_02.py
- python_scripts/03_basic_preprocessing_categorical_variables_exercise_02_solution.py
- python_scripts/04_basic_parameters_tuning.py
- python_scripts/04_basic_parameters_tuning_exercise_01.py
- python_scripts/04_basic_parameters_tuning_exercise_01_solution.py
- python_scripts/04_basic_parameters_tuning_exercise_02.py
- python_scripts/04_basic_parameters_tuning_exercise_02_solution.py
Not sure why it was needed at some point, but it seems to be fine now? Opening this PR to check this.
> Remove unecessary to_numpy.

- jupyter-book/_toc.yml
- python_scripts/cross_validation.py
- python_scripts/metrics.py
> ENH add notebook of cross-validation

- jupyter-book/_toc.yml
- python_scripts/feature_selection.py
> ENH Add feature selection notebook

- python_scripts/cross_validation.py
@glemaitre I started to do a pass. Have a quick glance at the diff but I would be in favor in quick merge and iterate.
> Fixes and improvements for the CV notebook

- python_scripts/linear_models_ex_01.py
- python_scripts/linear_models_sol_01.py
- python_scripts/linear_regression_without_sklearn.py
The function was using only a scatter plot and a plot.
We can repeat this way of plotting in the course instead of creating a function.
> ENH remove plotting function in linear model

- jupyter-book/_toc.yml
- jupyter-book/ensemble/ensemble_module_intro.md
- jupyter-book/evaluation/cross_validation_module_intro.md
- jupyter-book/evaluation/metrics_module_intro.md
- jupyter-book/feature_selection/feature_selection_module_intro.md
- jupyter-book/linear_models/linear_models_module_intro.md
- jupyter-book/predictive_modeling_pipeline/predictive_modeling_module_intro.md
- jupyter-book/trees/trees_module_intro.md
- python_scripts/03_categorical_pipeline_column_transformer.py
closes #115 
Add for each module the following:
- Give in plain English what the module is about
- Give the required skills for the module
- Point to resources to learning these skills
- Give the learning objectives
- Give the investment in time
> MNT add overview for each module

- jupyter-book/_toc.yml
- jupyter-book/ensemble/slides.md
- slides/ensemble.md
- slides/trees.md
Split slides ensemble and trees
> ENH split trees and ensemble slides

- jupyter-book/README.md
- jupyter-book/convert_exercises.py
- jupyter-book/ensemble/ensemble_quiz_01.md
- jupyter-book/ensemble/ensemble_quiz_02.md
- jupyter-book/ensemble/ensemble_quiz_03.md
- jupyter-book/evaluation/cross_validation_quiz.md
- jupyter-book/evaluation/metrics_quiz.md
- jupyter-book/feature_selection/feature_selection_quiz.md
- jupyter-book/interpretation/interpretation_quiz.md
- jupyter-book/linear_models/linear_models_quiz_01.md
- jupyter-book/linear_models/linear_models_quiz_02.md
- jupyter-book/linear_models/linear_models_quiz_03.md
- jupyter-book/linear_models/linear_models_quiz_04.md
- jupyter-book/ml_concepts/quiz.md
- jupyter-book/overfit/bias_vs_variance_quiz.md
- jupyter-book/overfit/learning_validation_curves_quiz.md
- jupyter-book/overfit/overfitting_vs_under_fitting_quiz.md
- jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz.md
- jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz.md
- jupyter-book/predictive_modeling_pipeline/03_categorical_pipeline_quiz.md
- jupyter-book/trees/trees_quiz_01.md
- jupyter-book/trees/trees_quiz_02.md
- jupyter-book/trees/trees_quiz_03.md
- jupyter-book/tuning/parameter_tuning_quiz.md
fix #137 
The idea is to  have exercises + solution in our private repo and generate the quizzs without solution with a Python script.
I did a first pass on the quizz solutions in our private repo and regenerate the quizzes plus added the Python script to do the automatic generation.
> Regenerate exercises from exercises with solution in our private repo.

- jupyter-book/_static/sklearn_mooc.js
My bad, custom javascript are not added to the bottom of body but to the head... So the script needs to wait for the document to be ready.
I also added the content_only url parameter.
> Add url param content_only and wait for page to be ready

- python_scripts/linear_models_regularization.py
> Reword sentence

- python_scripts/cross_validation_train_test.py
> Fix missing word

- python_scripts/02_numerical_pipeline_scaling.py
> Fix transformer description

- python_scripts/trees_ex_01.py
> Remove mismatching lines

- jupyter-book/tuning/parameter_tuning_module_intro.md
- python_scripts/parameter_tuning_manual.py
closes #173
Define what is an hyperparameters. Contrast it with model parameters for parametric model.
> Add defs of hyperparameter and contrast it with fitted parameters

- python_scripts/trees_hyperparameters.py
> Add some intuitions for other tree hyperparameters

- jupyter-book/evaluation/cross_validation_choices_index.md
- jupyter-book/overfit/overfit_take_away.md
- jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz.md
- jupyter-book/predictive_modeling_pipeline/predictive_modeling_module_intro.md
- jupyter-book/tuning/parameter_tuning_automated_quiz.md
- python_scripts/01_tabular_data_exploration.py
- python_scripts/02_numerical_pipeline_hands_on.py
- python_scripts/02_numerical_pipeline_introduction.py
- python_scripts/02_numerical_pipeline_scaling.py
- python_scripts/03_categorical_pipeline.py
- python_scripts/03_categorical_pipeline_column_transformer.py
- python_scripts/cross_validation_grouping.py
- python_scripts/cross_validation_learning_curve.py
- python_scripts/cross_validation_stratification.py
- python_scripts/cross_validation_train_test.py
- python_scripts/cross_validation_validation_curve.py
- python_scripts/parameter_tuning_automated.py
- python_scripts/parameter_tuning_manual.py
- python_scripts/trees_classification.py
- python_scripts/trees_dataset.py
- python_scripts/trees_ex_01.py
- python_scripts/trees_hyperparameters.py
- python_scripts/trees_regression.py
- python_scripts/trees_sol_01.py
- slides/README.md
- slides/ml_concepts.md
- slides/trees.md
We have some wrong explanations that have been merged. I am going to make a pass to detect them and fix them.
> FIX couple of improvements and corrections

- python_scripts/02_numerical_pipeline_introduction.py
closes #205
This PR introduce the terminology by defining a predictor, a predictive mode, and estimators.
It is place in the first notebook, early, avoiding any confusion.
> introduce the estimator terminology early

- python_scripts/linear_models_ex_04.py
- python_scripts/linear_models_sol_04.py
> change exercise about regularization to show correlation issues

- python_scripts/02_numerical_pipeline_scaling.py
- python_scripts/03_categorical_pipeline.py
close #179 
Add two notes instead of trying to get an artificial `ConvergenceWarning`
> remove ConvergenceWarning section and add notes

- python_scripts/03_categorical_pipeline.py
> remove figure to illustrate categorical encoding

- python_scripts/cross_validation_baseline.py
- python_scripts/cross_validation_grouping.py
- python_scripts/cross_validation_learning_curve.py
- python_scripts/cross_validation_nested.py
- python_scripts/cross_validation_sol_01.py
- python_scripts/cross_validation_train_test.py
- python_scripts/cross_validation_validation_curve.py
- python_scripts/ensemble_hyperparameters.py
- python_scripts/feature_selection_introduction.py
- python_scripts/feature_selection_limitation_model.py
- python_scripts/linear_models_regularization.py
- python_scripts/parameter_tuning_automated.py
> replace empirical and generalization by testing and training

- python_scripts/cross_validation_nested.py
- python_scripts/ensemble_ex_01.py
- python_scripts/ensemble_introduction.py
- python_scripts/ensemble_sol_01.py
- python_scripts/feature_selection_introduction.py
- python_scripts/linear_models_regularization.py
> remove fine-tune for hyperparameter tuning

- .circleci/config.yml
- build_tools/circle/build_jupyter_book.sh
- environment-dev.yml
- requirements-dev.txt
- requirements.txt
> MNT add requirement and environment for dev

- jupyter-book/_toc.yml
- jupyter-book/linear_models/linear_models_wrap_up_quiz.md
- jupyter-book/overfit/learning_validation_curves_quiz.md
- jupyter-book/overfit/overfitting_vs_under_fitting_quiz.md
- jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz.md
- jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md
- jupyter-book/tuning/parameter_tuning_automated_quiz.md
> update linear model wrap-up quiz

- jupyter-book/_toc.yml
- jupyter-book/overfit/overfit_wrap_up_quiz.md
> add wrap-up quiz for select the best model module

- notebooks/01_tabular_data_exploration.ipynb
- notebooks/02_numerical_pipeline_ex_01.ipynb
- notebooks/02_numerical_pipeline_sol_01.ipynb
- notebooks/cross_validation_baseline.ipynb
- notebooks/cross_validation_ex_01.ipynb
- notebooks/cross_validation_learning_curve.ipynb
- notebooks/cross_validation_sol_01.ipynb
- notebooks/cross_validation_validation_curve.ipynb
- notebooks/ensemble_ex_01.ipynb
- notebooks/ensemble_ex_03.ipynb
- notebooks/ensemble_ex_04.ipynb
- notebooks/ensemble_ex_05.ipynb
- notebooks/ensemble_gradient_boosting.ipynb
- notebooks/ensemble_hist_gradient_boosting.ipynb
- notebooks/ensemble_hyperparameters.ipynb
- notebooks/ensemble_introduction.ipynb
- notebooks/ensemble_random_forest.ipynb
- notebooks/ensemble_sol_01.ipynb
- notebooks/ensemble_sol_03.ipynb
- notebooks/ensemble_sol_04.ipynb
- notebooks/ensemble_sol_05.ipynb
- notebooks/linear_models_ex_01.ipynb
- notebooks/linear_models_ex_02.ipynb
- notebooks/linear_models_ex_03.ipynb
- notebooks/linear_models_regularization.ipynb
- notebooks/linear_models_sol_02.ipynb
- notebooks/linear_models_sol_03.ipynb
- notebooks/metrics_classification.ipynb
- python_scripts/metrics_classification.py
> FIX add dummy classifier in ROC AUC curve

- jupyter-book/_toc.yml
- jupyter-book/appendix/acknowledgement.md
> FIX add attributions in acknowledgements for figures

- jupyter-book/_toc.yml
- python_scripts/02_numerical_pipeline_ex_00.py
- python_scripts/02_numerical_pipeline_sol_00.py
This is my attempt at a simple numerical data with k-neighbors classifier.
Note: I originally wanted to do the `n_neighbors=1` 100% accuracy on the train set but not on the test set. Unfortunately life is always more complicated than you think 😢. Because there are many duplicated rows (in this numerical-only dataset, we have 4 features `age`, `hours-per-week`, `capital-gain`, `capital-loss`) with different classes the accuracy is not 100% on the train set.
Not only it does not overfit with `n_neighbors=1` but it actually even underfits (it performs about the same as a majority class predictor both on the train and test set)  for some reason that I let as an exercise for the astute reader.
> Add simple numerical data exercise.

- jupyter-book/index.md
Also change numpy link to be less confusing (go to content rather than
overwhelming table of contents)
> Add matplotlib requirement in the course intro.

- jupyter-book/_toc.yml
- jupyter-book/appendix/glossary.md
closes #38 
First attempt to add a glossary
> ENH add a glossary with some terminology

- jupyter-book/_static/sklearn_mooc.js
> Hide hypothesis elements in content_only mode

- python_scripts/trees_classification.py
closes: https://mooc-forums.inria.fr/moocsl/t/typo-decisison-tree-in-classification/519
> FIX correct inversion of feature culmen depth/length in tree

- python_scripts/02_numerical_pipeline_hands_on.py
- python_scripts/03_categorical_pipeline.py
- python_scripts/03_categorical_pipeline_column_transformer.py
> FIX always drop education-num and keep quite with this detail

- python_scripts/02_numerical_pipeline_introduction.py
closes https://mooc-forums.inria.fr/moocsl/t/add-nearest-neighbors-explanation-when-we-introduce-it/441
> FIX add a quick explanation of a kNN

- jupyter-book/overfit/overfitting_vs_under_fitting_quiz.md
> FIX simplify quiz 5

- jupyter-book/tuning/parameter_tuning_automated_quiz.md
closes #290
see https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/14
> FIX add more instructions to select models in parallel coordinate plot

- jupyter-book/tuning/parameter_tuning_wrap_up_quiz.md
closes #295 
see also https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/15
> FIX move hints in instruction in wrap up quiz

- jupyter-book/evaluation/evaluation_wrap_up_quiz.md
closes #275 
see also https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/17
> ENH add a simple question in evaluation wrap up quiz

- jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz.md
closes #308 
see also https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/18
> FIX remove ambuiguity in numerical pipeline quiz

- python_scripts/linear_models_ex_02.py
- python_scripts/linear_models_sol_02.py
- python_scripts/linear_regression_non_linear_link.py
- python_scripts/linear_regression_without_sklearn.py
- python_scripts/metrics_regression.py
- python_scripts/trees_regression.py
> FIX change color scatter plot for consistency

- python_scripts/02_numerical_pipeline_scaling.py
> ENH be more general in presenting cross-validation

- python_scripts/ensemble_ex_01.py
- python_scripts/ensemble_ex_02.py
- python_scripts/ensemble_ex_03.py
- python_scripts/ensemble_ex_04.py
- python_scripts/ensemble_gradient_boosting.py
- python_scripts/ensemble_hist_gradient_boosting.py
- python_scripts/ensemble_hyperparameters.py
- python_scripts/ensemble_sol_01.py
- python_scripts/ensemble_sol_02.py
- python_scripts/ensemble_sol_03.py
- python_scripts/ensemble_sol_04.py
- python_scripts/linear_models_regularization.py
- python_scripts/linear_regression_in_sklearn.py
closes https://mooc-forums.inria.fr/moocsl/t/avoid-switching-between-different-metrics-if-possible/552
closes https://mooc-forums.inria.fr/moocsl/t/explain-r2-score-the-first-time-we-introduce-it/536/2
closes https://mooc-forums.inria.fr/moocsl/t/use-mean-absolute-error-in-the-exercise-as-in-previous-notebook/534
> FIX be more consistent with regression metrics used

- python_scripts/03_categorical_pipeline.py
closes https://mooc-forums.inria.fr/moocsl/t/do-a-short-summary-about-one-hot-vs-ordinal-encoding/514/4
> FIX Add summary regarding categorical encoding

- python_scripts/03_categorical_pipeline.py
- python_scripts/03_categorical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_sol_01.py
closes https://mooc-forums.inria.fr/moocsl/t/exercise-m1-04/541
> ENH improve directive in exercise M1.04

- python_scripts/02_numerical_pipeline_hands_on.py
- python_scripts/02_numerical_pipeline_introduction.py
- python_scripts/02_numerical_pipeline_scaling.py
- python_scripts/03_categorical_pipeline.py
- python_scripts/03_categorical_pipeline_column_transformer.py
- python_scripts/cross_validation_baseline.py
- python_scripts/cross_validation_train_test.py
- python_scripts/ensemble_introduction.py
- python_scripts/feature_selection_introduction.py
- python_scripts/linear_regression_non_linear_link.py
- python_scripts/linear_regression_without_sklearn.py
- python_scripts/parameter_tuning_manual.py
- python_scripts/trees_classification.py
closes #326
Once upon a time, I added too many notes. Some redundant notes regarding basic could be removed.
> FIX remove redundant notes that clutter the notebooks

- python_scripts/02_numerical_pipeline_ex_01.py
- python_scripts/02_numerical_pipeline_hands_on.py
- python_scripts/02_numerical_pipeline_introduction.py
- python_scripts/02_numerical_pipeline_scaling.py
- python_scripts/03_categorical_pipeline_column_transformer.py
closes https://mooc-forums.inria.fr/moocsl/t/various-points-for-section-fitting-a-scikit-learn-model-on-numerical-data/540
> FIX address some feedback from forum 

- python_scripts/cross_validation_ex_01.py
- python_scripts/cross_validation_learning_curve.py
- python_scripts/cross_validation_sol_01.py
- python_scripts/cross_validation_validation_curve.py
closes https://mooc-forums.inria.fr/moocsl/t/various-points-for-section-validation-and-learning-curves/545
> FIX address review forum

- python_scripts/cross_validation_train_test.py
closes https://mooc-forums.inria.fr/moocsl/t/various-points-for-section-overfitting-and-underfitting/544
> FIX address comments from forum

- python_scripts/02_numerical_pipeline_sol_01.py
closes https://mooc-forums.inria.fr/moocsl/t/inconsistency-lecture-solution-to-notebook-m1-03/1855/2
> FIX change random_state for consistency

- python_scripts/02_numerical_pipeline_ex_01.py
closes https://mooc-forums.inria.fr/moocsl/t/duplicate-cells-in-exercise-m1-03-notebook/992
> FIX remove duplicated cell in exercise M1.03

- notebooks/parameter_tuning_sol_02.ipynb
- python_scripts/parameter_tuning_sol_02.py
closes https://mooc-forums.inria.fr/moocsl/t/wrong-values-in-solution-to-exercice-m3-01/2640
> FIX typo regarding solution

- python_scripts/parameter_tuning_randomized_search.py
Since we want to usE this distribution to create integer
> Fix typo in parameter_tuning_randomized_search.py

- environment-dev.yml
- jupyter-book/_toc.yml
- requirements-dev.txt
Ran `jupyter-book toc migrate _toc.yml -o _toc.yml` and added back some emoticons 🚧 which had been converted by the migration tool.
> Update _toc.yml after jupyter-book 0.11

- python_scripts/03_categorical_pipeline.py
See link below for rules on the use of a/an
https://forum.wordreference.com/threads/a-an-unitary.42391/
> FIX grammar

- python_scripts/03_categorical_pipeline_ex_02.py
A bit of rephrasing and grammar fixing
> FIX-wording

- notebooks/cross_validation_ex_01.ipynb
- notebooks/cross_validation_learning_curve.ipynb
- notebooks/cross_validation_train_test.ipynb
- notebooks/cross_validation_validation_curve.ipynb
- python_scripts/cross_validation_ex_01.py
- python_scripts/cross_validation_learning_curve.py
- python_scripts/cross_validation_train_test.py
- python_scripts/cross_validation_validation_curve.py
PR includes the .ipynb files already built
> Fix typos and wording

- python_scripts/cross_validation_sol_01.py
I edited the ex files but forgot to make the same modifications to the sol files. This fixes it.
> FIX edit solution files

- python_scripts/cross_validation_ex_01.py
- python_scripts/cross_validation_sol_01.py
Fix #394 (incomplete PR in cross_validations_ex_01.py) and
fix #397 (merged typos in cross_validations_sol_01.py)
> Fix merged typos in cross-validations .py files

- .circleci/artifact_path
- .github/workflows/circleci-artifacts-redirector.yml
- build_tools/circle/build_jupyter_book.sh
- jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz_m1_01.md
- python_scripts/01_tabular_data_exploration.py
> Make it easier to access affected files in PR

- Makefile
- build_tools/generate-exercise-from-solution.py
- generate_exercise_from_solution.py
- python_scripts/01_tabular_data_exploration_ex_01.py
- python_scripts/01_tabular_data_exploration_sol_01.py
- python_scripts/02_numerical_pipeline_ex_00.py
- python_scripts/02_numerical_pipeline_ex_01.py
- python_scripts/02_numerical_pipeline_sol_00.py
- python_scripts/02_numerical_pipeline_sol_01.py
- python_scripts/03_categorical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_ex_02.py
- python_scripts/03_categorical_pipeline_sol_01.py
- python_scripts/03_categorical_pipeline_sol_02.py
> Generate exercises from the solutions and fix problems in first module exercises

- jupyter-book/appendix/glossary.md
Fix #406 (remaining statistical performance in Glossary)
> Fix #406 (remaining statistical performance)

- python_scripts/linear_regression_without_sklearn.py
Minor wording to avoid repeating ourselves
> Fix redundant text in linear_regression_without_sklearn.py

- python_scripts/linear_models_sol_01.py
PR #422 erased a hint in [exercise M4.01](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_ex_01.html).
This fixes it while improving wording.
> Fix regenerate exercise M4.01 from solution

- python_scripts/trees_sol_01.py
Using [this notebook](https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/blob/master/Bilans/detailed_quiz_results_analysis.ipynb) we see that Q2 in quiz M5.02 has a score barely above 0.6. Adding a small paragraph to explain the difference between split nodes and leaves may help clarifying this question.
> Explain difference between nodes and leaves

- jupyter-book/ensemble/ensemble_quiz_m6_04.md
- jupyter-book/ensemble/ensemble_wrap_up_quiz.md
- jupyter-book/evaluation/evaluation_wrap_up_quiz.md
- jupyter-book/linear_models/linear_models_wrap_up_quiz.md
- jupyter-book/trees/trees_wrap_up_quiz.md
closes #405 
closes #429 
Addresses #405 and #429. I will make a PR in `gitlab` implementing the equivalent changes.
Even if the changes concern the quizzes, it should be ok to merge this branch, as they are a change in form and not in substance.
> Rename "statistical performance" -> "generalization performance"

- build_tools/generate-md-index.py
- full-index.md
Fixes #111.
This is useful for people that want to run the notebooks locally and also when giving courses that reuse the MOOC material so that people can more easily follow along.
I think manually creating indexes from the full one is the way to go (e.g. Inria Academy context).
> Add script to generate full index

- python_scripts/cross_validation_grouping.py
Tweak to remove line of code importing seaborn, as it is no longer necessary since  #250.
> MNT Erase unused line of code

- python_scripts/03_categorical_pipeline.py
- python_scripts/linear_models_regularization.py
> Replace deprecated get_feature_names by get_feature_names_out

- jupyter-book/evaluation/evaluation_quiz_m7_02.md
- jupyter-book/evaluation/evaluation_quiz_m7_04.md
- jupyter-book/evaluation/evaluation_quiz_m7_05.md
- jupyter-book/linear_models/linear_models_wrap_up_quiz.md
- jupyter-book/overfit/learning_validation_curves_quiz_m2_02.md
- jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz_m1_02.md
Synchronizes quizzes that were modified from version 1.0 of the MOOC
> Synchronize edited quizzes

- Makefile
- build_tools/sanity-check.py
- notebooks/03_categorical_pipeline.ipynb
- notebooks/helpers/plotting.py
- notebooks/linear_models_regularization.ipynb
- python_scripts/ensemble_adaboost.py
- python_scripts/helpers/plotting.py
- python_scripts/linear_models_ex_05.py
- python_scripts/linear_models_sol_05.py
- python_scripts/logistic_regression.py
- python_scripts/logistic_regression_non_linear.py
- python_scripts/trees_classification.py
- python_scripts/trees_ex_01.py
- python_scripts/trees_sol_01.py
Replace the `plot_decision_function` by a new display `DecisionBoundaryDisplay`.
We intend to add this display in `scikit-learn`. Thus, we place the import in a helper plotting module. In the future, only the import will be modified (together with a brief explanation regarding this class).
> MNT update plot_decision_function by DecisionBoundaryDisplay

- jupyter-book/index.md
So that people who find this page know what is up-coming
> Announce: mention the new MOOC coming

- full-index.md
- python_scripts/cross_validation_train_test.py
> Rename cross-validation framework

- python_scripts/ensemble_hist_gradient_boosting.py
closes #443 
Remove "drastically" and rephrase the part about integer values.
> Fix wording in HGBDT notebook

- python_scripts/03_categorical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_sol_01.py
> Add note advising for error_score='raise' to debug

- .circleci/config.yml
Let's see if the output of the solution to the tree ensemble work now.
> Invalidate jupyter-book cache

- python_scripts/trees_hyperparameters.py
closes #510 
Use the display to simplify the huge amount of matplotlib code in the notebook.
> use DecisionBoundaryDisplay in tree hyperparameter

- python_scripts/03_categorical_pipeline_sol_02.py
- python_scripts/cross_validation_sol_02.py
- python_scripts/parameter_tuning_nested.py
closes #304 
It remains the last question of the following wrap-up quiz: https://inria.github.io/scikit-learn-mooc/tuning/parameter_tuning_wrap_up_quiz.html
I will check in another PR since it requires some testing.
> remove significantly whenever linked to statistical meaning

- jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_video_cross_validation.md
- jupyter-book/tuning/parameter_tuning_parallel_plot_video.md
Two more videos were recently added to YouTube, therefore this PR updates #497.
> Update available videos

- notebooks/parameter_tuning_parallel_plot.ipynb
- python_scripts/parameter_tuning_parallel_plot.py
Closes #531.
Still open to discussion if this is the right solution.
> Change parallel plot notebook title

- notebooks/ensemble_ex_04.ipynb
- notebooks/ensemble_sol_04.ipynb
- python_scripts/ensemble_ex_04.py
- python_scripts/ensemble_sol_04.py
Follow-up of removing an ensemble exercise
> Fix ensemble exercise numbering

- jupyter-book/_toc.yml
- jupyter-book/concluding_remarks.md
- slides/Makefile
- slides/concluding_remarks.md
Closes #261.
This now has the text corresponding to the video and a little more that we had removed to make the video shorter.
> MRG: Concluding remarks

- python_scripts/01_tabular_data_exploration.py
- python_scripts/01_tabular_data_exploration_ex_01.py
- python_scripts/01_tabular_data_exploration_sol_01.py
The main change in this PR is changing the markdown notation `feature_name` -> `"feature_name"`.
It also introduces several tweaks: fix typos, fix grammar and code formatting for the tabular data sequence in M1.
Not sure if this even needs review.
> Tabular data tweaks

- README.md
- jupyter-book/index.md
Closes #561.
PR so that people who find this page know the dates for the current session
> Update announce: mention the dates of the new MOOC session

- jupyter-book/concluding_remarks.md
> Move content to admonition to remove it from FUN

- jupyter-book/_config.yml
> Fix the binder launch button

- python_scripts/01_tabular_data_exploration_ex_01.py
- python_scripts/02_numerical_pipeline_ex_00.py
- python_scripts/02_numerical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_ex_02.py
- python_scripts/03_categorical_pipeline_sol_02.py
- python_scripts/cross_validation_ex_01.py
- python_scripts/cross_validation_ex_02.py
- python_scripts/cross_validation_sol_01.py
- python_scripts/ensemble_ex_01.py
- python_scripts/ensemble_ex_02.py
- python_scripts/ensemble_ex_03.py
- python_scripts/ensemble_ex_04.py
- python_scripts/feature_selection_ex_01.py
- python_scripts/linear_models_ex_01.py
- python_scripts/linear_models_ex_02.py
- python_scripts/linear_models_ex_03.py
- python_scripts/linear_models_ex_04.py
- python_scripts/linear_models_ex_05.py
- python_scripts/linear_models_sol_01.py
- python_scripts/linear_models_sol_02.py
- python_scripts/metrics_ex_01.py
- python_scripts/metrics_ex_02.py
- python_scripts/parameter_tuning_ex_02.py
- python_scripts/parameter_tuning_ex_03.py
- python_scripts/trees_ex_01.py
- python_scripts/trees_ex_02.py
- python_scripts/trees_sol_01.py
Closes #578.
This header was not necessary. I am only removing the header from the *.py files
> Remove utf-8 header

- jupyter-book/linear_models/linear_models_quiz_m4_03.md
Related to #590. Do not close Issue until changes have been done in FUN.
> Fix inexact wording in M4.03 Q1

- jupyter-book/linear_models/linear_models_quiz_m4_03.md
Wording in #591 was still not optimal. This fixes it.
> Improve wording in M4.03 Q1 even more

- jupyter-book/_config.yml
- jupyter-book/_static/sklearn_mooc.css
> Add formatting for add to join MOOC

- jupyter-book/index.md
Partially addresses #593.
I also took the liberty of changing [note -> notice](https://www.quora.com/What-is-the-difference-between-note-and-notice-1) as I felt it was more suitable, but I don't have strong opinions on that.
> Add reference to youtube playlist in index

- python_scripts/01_tabular_data_exploration.py
As discussed in [this forum post](https://mooc-forums.inria.fr/moocsl/t/imbalance-male-female-samples/8055) there is an important imbalance on the data collection concerning the number of male/female samples in the adult_census dataset. Even if we don't really talk about fairness until the Concluding remarks, this PR adds a comment to raise awareness on data-imbalance impact on real life applications.
Be aware that this can be **perceived** as a political statement, so we will have to chose our words carefully.
> Add comment on fairness of the adult_census imbalance

- python_scripts/linear_regression_without_sklearn.py
Closes #601.
On a side note, I changed "in function of" -> "as a function of" as mentioned in [this stackexchange post](https://english.stackexchange.com/questions/30547/is-the-phrase-in-function-of-proper-english).
> Fix scatterplot title in M4

- python_scripts/01_tabular_data_exploration.py
- python_scripts/ensemble_gradient_boosting.py
- python_scripts/feature_selection_introduction.py
- python_scripts/linear_models_regularization.py
- python_scripts/parameter_tuning_nested.py
here's a few changes that you might want to adopt in the wording
also I tried to `make` the .ipynb's
I noticed a few missing deps, that I recorded in the dev requirements file
there's still something fishy though, probably a dependency that needs pinning (see below)
I figured you guys'd be able to update the ipynb's separately if necessary
----
in any case here's what I get
```
$ pip show myst_parser
Name: myst-parser
Version: 0.17.0
$ make
... <snip>
File "/Users/tparment/git/scikit-learn-mooc/build_tools/convert-python-script-to-notebook.py", line 99, in replace_admonition_in_cell_source
config = MdParserConfig(renderer="docutils")
TypeError: __init__() got an unexpected keyword argument 'renderer'
make: *** [notebooks/01_tabular_data_exploration.ipynb] Error 1
```
> to choose and not to chose

- python_scripts/01_tabular_data_exploration.py
- python_scripts/02_numerical_pipeline_introduction.py
Hi, found one typo while reading the code, and one example in the intro chapter that didn't use the target column.
I tried running the Python script, but that didn't modify the Notebook file? I couldn't find instructions on how to re-generate the notebooks, so if anyone could direct me to how to generate these, I can then amend this PR :+1: 
Thanks!!! :nerd_face:
> Use a variable for the target column as in the other examples, fix typo

- jupyter-book/tuning/parameter_tuning_module_intro.md
- python_scripts/parameter_tuning_nested.py
- python_scripts/parameter_tuning_randomized_search.py
Not a native, so feel free to check with a native speaker if needed :+1: 
Thanks!
Bruno
> Remove some words or fix typos

- python_scripts/cross_validation_nested.py
Not really sure if the intended word was minimal?
Getting close to the end of the course! Thanks!
> Fix typo s/minal/minimal

- python_scripts/01_tabular_data_exploration.py
- avoid long sentences
- add more repetition of important connections
- add more references to what is meant in the notebook
- one small fix to orthography
Would be interesting to hear your review on these small changes.
> reduce the complexity of language

- python_scripts/02_numerical_pipeline_cross_validation.py
- python_scripts/02_numerical_pipeline_hands_on.py
- python_scripts/02_numerical_pipeline_introduction.py
These are really minor things, but I hope they can improve the reading experience. Please let me know how you like the `Notebook Recap` idea that I also introduced with #652
> language fixes to ease reading

- python_scripts/03_categorical_pipeline.py
the `handle_unknown` confused my learners a lot. Here is a suggestion to improve it.
> refine the explanation of the handle_unknown parameter

- python_scripts/01_tabular_data_exploration.py
Previous wording was not exact.
> Improve paragraph on data imbalance

- jupyter-book/evaluation/evaluation_wrap_up_quiz.md
I guess only Wrap-up quiz M7 was not updated in the github repo.
> MAINT synchronize quizzes

- README.md
- jupyter-book/index.md
> Add "how to cite us" info to README and index.md

- jupyter-book/_config.yml
> Disable thebe integration

- .github/workflows/slides.yml
- check_env.py
- environment-dev.yml
- environment.yml
> Remove deprecated distutils.Version in check_env.py

- python_scripts/logistic_regression.py
- python_scripts/logistic_regression_non_linear.py
- python_scripts/parameter_tuning_grid_search.py
- python_scripts/parameter_tuning_nested.py
- python_scripts/parameter_tuning_randomized_search.py
We seem to have some remaining `set_config(display="diagram")` scattered in the MOOC.
This PR fixes it, but we still need to build the notebooks afterwards.
> MAINT Remove remaining set_config

- jupyter-book/_config.yml
> feat: Adds license to jupyter-book config

- python_scripts/parameter_tuning_ex_02.py
- python_scripts/parameter_tuning_sol_02.py
This PR also makes a bit more explicit the instructions to the exercise.
> MAINT Change parameter names to match scikit-learn notation

- CONTRIBUTING.md
- README.md
This seems a better landing place
> MNT Modify the Binder links to go to full-index.ipynb

- python_scripts/01_tabular_data_exploration_ex_01.py
- python_scripts/02_numerical_pipeline_ex_00.py
- python_scripts/02_numerical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_ex_01.py
- python_scripts/03_categorical_pipeline_ex_02.py
- python_scripts/cross_validation_ex_01.py
- python_scripts/cross_validation_ex_02.py
- python_scripts/ensemble_ex_01.py
- python_scripts/ensemble_ex_02.py
- python_scripts/ensemble_ex_03.py
- python_scripts/ensemble_ex_04.py
- python_scripts/feature_selection_ex_01.py
- python_scripts/linear_models_ex_01.py
- python_scripts/linear_models_ex_02.py
- python_scripts/linear_models_ex_03.py
- python_scripts/linear_models_ex_04.py
- python_scripts/linear_models_ex_05.py
- python_scripts/metrics_ex_01.py
- python_scripts/metrics_ex_02.py
- python_scripts/parameter_tuning_ex_02.py
- python_scripts/parameter_tuning_ex_03.py
- python_scripts/trees_ex_01.py
- python_scripts/trees_ex_02.py
I don't think there are important changes but just in case.
> MAINT: synchronize exercises

- python_scripts/metrics_sol_02.py
Fixes #323.
To keep the idea of having this as extra material, it is hidden in the solution of the exercise.
Optionally we can also mention pinball loss, but I felt that we don't want to enter into the details of what different loss functions do.
> Introduce that evaluation metrics and loss are not always the same

- python_scripts/linear_models_regularization.py
Follows #698, which I merged without a proper final pass.
Hopefully this PR improves some final details.
> Various fixes and improvements in Regularization of linear regression model

- jupyter-book/evaluation/evaluation_quiz_m7_02.md
- jupyter-book/evaluation/evaluation_quiz_m7_05.md
- jupyter-book/linear_models/linear_models_quiz_m4_02.md
- jupyter-book/linear_models/linear_models_quiz_m4_05.md
- jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz_m1_01.md
- jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz_m1_02.md
- jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md
- jupyter-book/tuning/parameter_tuning_automated_quiz_m3_02.md
- jupyter-book/tuning/parameter_tuning_manual_quiz_m3_01.md
From the private repo with solutions.
> Synchronize quiz

- python_scripts/linear_models_sol_02.py
- python_scripts/linear_regression_non_linear_link.py
Follows #701, were we removed one exercise. This PR removes the narrative references made to it.
> MAINT fix narrative according to new order of M4

- python_scripts/parameter_tuning_randomized_search.py
This PR improves wording by preferring verbs in present mode and clarifying certain points.
> MAINT improve wording and fix typo

- README.md
This PR updates old info about the FUN session.
> MAINT Update dates for FUN session

- python_scripts/linear_regression_without_sklearn.py
In real life I got some feedback suggesting we mention that the values we set are arbitrary, as we have not yet fitted any OLS.
This PR also takes the opportunity to prefer present mode verbs.
> MAINT Improve wording in linear regression intro

- python_scripts/logistic_regression.py
Follows #722.
This PR is aims to:
- improve wording;
- prepare for possible quiz questions on the shape of the output of `predict_proba`;
- introduce intuitions on the shape of the logistic function.
Side effects:
- introduces way to access pipeline steps as intended in #435;
- moves mathematical explanation on straight lines to a more pertinent place.
> Iter on contents related to predict_proba

- python_scripts/linear_models_sol_02.py
Fixes typo in variable name introduced in #717.
> FIX typo in variable name

- python_scripts/trees_hyperparameters.py
I found that these two paragraphs were a bit redundant and I decided to keep the first.
This is my first pull request and I am happy to contribute to the mooc :)
> Remove redundant text

- python_scripts/parameter_tuning_ex_02.py
- python_scripts/parameter_tuning_ex_03.py
- python_scripts/parameter_tuning_grid_search.py
- python_scripts/parameter_tuning_nested.py
- python_scripts/parameter_tuning_parallel_plot.py
- python_scripts/parameter_tuning_sol_02.py
- python_scripts/parameter_tuning_sol_03.py
- python_scripts/trees_dataset.py
- python_scripts/trees_ex_02.py
- python_scripts/trees_hyperparameters.py
- python_scripts/trees_regression.py
- python_scripts/trees_sol_02.py
This PR addresses this comment https://github.com/INRIA/scikit-learn-mooc/pull/744#issuecomment-1783051071
> change verbs to present mode in modules 3 and 5

- python_scripts/parameter_tuning_nested.py
Correct typo reported in:
https://mooc-forums.inria.fr/moocsl/t/another-typo/15668
> FIX typo in description

- python_scripts/linear_models_feature_engineering_classification.py
Fix a typo reported in:
https://mooc-forums.inria.fr/moocsl/t/this-is-such-a-great-course/15689
> FIX fix some typos

- jupyter-book/_config.yml
> added copyright key to indicate correct year

- jupyter-book/tuning/parameter_tuning_manual_quiz_m3_01.md
- notebooks/cross_validation_ex_01.ipynb
- python_scripts/cross_validation_learning_curve.py
- python_scripts/cross_validation_train_test.py
I fixed several small typos - see the individual commits for details.
> FIX fix several small typos

- python_scripts/parameter_tuning_grid_search.py
Just discovered while teaching this notebook.
> remove dublicate word

- CITATION.cff
Follow-up from https://github.com/INRIA/scikit-learn-mooc/issues/651. I tested CITATION.cff in a test repo and this seems to do the job.
> MNT Add CITATION.cff

- python_scripts/datasets_california_housing.py
Fixing a minor typo in `datasets_california_housing.py`
> Fix minor typo in `datasets_california_housing.py`

- python_scripts/parameter_tuning_grid_search.py
> Add label to colorbar in sns.heatmap

- .gitignore
- Makefile
- build_tools/generate-wrap-up.py
Added a script to generate only the python part of the wrap up quizzes to allow for a check of the answers with sklearn 1.6.
> MTN Wrap up quiz sklearn 1.6 verification

- jupyter-book/linear_models/linear_models_wrap_up_quiz.md
- jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md
- jupyter-book/trees/trees_wrap_up_quiz.md
- jupyter-book/tuning/parameter_tuning_wrap_up_quiz.md
- notebooks/metrics_ex_02.ipynb
- python_scripts/metrics_ex_02.py
I ran `make` on `main` and there were a few files out of sync.
> Sync quizzes, exercises and notebooks

- notebooks/ensemble_ex_03.ipynb
- notebooks/ensemble_sol_03.ipynb
- python_scripts/ensemble_ex_03.py
- python_scripts/ensemble_sol_03.py
As discussed in [issue 809](https://github.com/INRIA/scikit-learn-mooc/issues/809), I add the advise not to tune `n_estimators`. Moreover, I add the validation curve for this hyperparameter as that is what is asked for in the exercise. Please feel free to adjust the wording as you like.
> Add validation curve for n_estimators plus advise on (not) tuning

- notebooks/cross_validation_baseline.ipynb
- notebooks/cross_validation_time.ipynb
- python_scripts/cross_validation_baseline.py
- python_scripts/cross_validation_time.py
Follow-up from #819. See also #786.
> Iterate on the interpretation of R2 score

- full-index.ipynb
- notebooks/cross_validation_time.ipynb
- notebooks/parameter_tuning_sol_03.ipynb
I deleted the contents of the `notebooks/` and reran `make notebooks` to force a rerender of all the notebooks, and this caught some unsynced notebooks.
I also resynced the index.
> Missing notebook sync

- requirements.txt
> MAINT Update matplotlib to v3.10.3

- jupyter-book/evaluation/evaluation_wrap_up_quiz.md
- jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md
Fixes #840 .
Added the sync of the quizzes 1 and 7 per the issues [101](https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/101) and [100](https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/100) on gitlab.
> MTN Synchronized the quizzes for module 1 and 7
