Makefile
build_scripts/convert-python-script-to-notebook.sh

If the notebook execution fails, `rendered_notebook/the_notebook_name.ipynb` is generated empty and running `make` again will not trigger a rebuild.
This PR fixes this problem. It also moves the logic to an external script because I am getting annoyed by the `Makefile` limitations and I don't want to have to remember all these quirks ...

Improve Makefile to make sure rendered notebook is not empty

---

requirements.txt

Due to https://github.com/matplotlib/matplotlib/issues/18254.
Example build failure: https://app.circleci.com/pipelines/github/INRIA/scikit-learn-mooc/155/workflows/9e1b06a1-af33-4c96-95d3-c0114df6be2e/jobs/156
Pinning to matplotlib 3.3.0 until 3.3.2 is released.

Pin matplotlib to avoid matplotlib 3.3.1 regression

---

python_scripts/ensemble.py

I think we could expand/give more intuition on the need for the 'base' ensemble estimators to be 'weak' (/not ideal) learners (for both bagging and boosting) and how this avoids overfiting. Maybe e.g., combining weak learners that each focus, not too strongly, on one area/relationship is better than using a 'stronger' learner which is likely to overfit (as it is allowed to 'focus' too much). 
And how/why the bootstrap samples result in 'weak' learners.

Ensemble grammar, typo, re-wording

---

python_scripts/linear_models.py

Some grammar, typo and minor re-wording changes to `linear_models.py`. Happy to change back the more opinionated changes!
Some suggestions:
* We use the terms formula/formulate, rule and model (sometimes a bit interchangeably) but we never explicitly explain the relationship between them/what a model is e.g., a model is a formula for relating features to target. We do talk about it a bit in the first notebook but it's not clearly relating 'model' to 'rule': 
https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/01_tabular_data_exploration.py#L202-203
* We switch between using the terms infer/inference & predict/prediction. This is a nitpick but I think we should consistently only
use one term or explain that they mean the same thing.
* Might not be necessary but should we …

Linear - grammar, minor re-wording, typos

---

python_scripts/trees.py

Nice notebook.
I would have liked to see the decision tree plot (with arrows and boxes) earlier and to show it with the plots of decision boundary - it is a nice way to visualise the splits. It also makes it obvious that the splits are done per box/partition (i.e., for the 2nd level you need 2 splits, one for each partition).
I will put specific comments at the relevant sections.

Tree - grammar, typos and some re-wording

---

python_scripts/metrics.py

For me the notation `:math:` does not render properly. I think jupyter notebook uses `$ $` notation?
Nitpick - consistently use either mislabel or misclassify.
We could also more explicitly talk about how accuracy is affected by the threshold picked but ROC-AUC and average recall does not, as calculating involves using many thresholds.
Specific comments in review.

Metrics - grammar, typo, some re-wording

---

.github/workflows/circleci-artifacts-redirector.yml

This would be easier to see the generated website directly in a PR.

Add CI status to point directly to CircleCI website.

---

notebooks/02_numerical_pipeline.ipynb
notebooks/02_numerical_pipeline_ex_01.ipynb
notebooks/02_numerical_pipeline_scaling.ipynb
notebooks/02_numerical_pipeline_sol_01.ipynb
notebooks/03_categorical_pipeline.ipynb
notebooks/03_categorical_pipeline_column_transformer.ipynb
notebooks/03_categorical_pipeline_ex_01.ipynb
notebooks/03_categorical_pipeline_ex_02.ipynb
notebooks/03_categorical_pipeline_sol_01.ipynb
notebooks/03_categorical_pipeline_sol_02.ipynb
python_scripts/02_numerical_pipeline.py
python_scripts/02_numerical_pipeline_ex_01.py
python_scripts/02_numerical_pipeline_scaling.py
python_scripts/02_numerical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline_sol_02.py

Although not exactly the same, this feels simpler to use `dtype_include=object` rather than `dtype_exclude=["int", "float"]`

Fix dtype filtering on int error on Windows.

---

python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline_sol_02.py

Fix #93 
Fixed long markdown lines while I was at it (and also a few `OneHotEncoding` rather than `OneHotEncoder`)
In practice this kind of inconsistency make people struggle while they try to do the exercises because they copy and paste from a different notebook where the code is slightly different (e.g. variable names or in this case binary encoding of sex or not).

Use binary encoding for sex in exercise for consistency.

---

python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/04_parameter_tuning.py
python_scripts/04_parameter_tuning_search.py
python_scripts/04_parameter_tuning_sol_02.py

close #120 
Specifying the columns in both `OrdinalEncoder` and `OneHotEncoder` for consistency.
Since we do so, we can use `drop="if_binary"` in `OneHotEncoder`.
I also make some small improvement regarding some description.
In the future:
* `OrdinalEncoder` will handle rare categories.
* `OneHotEncoding` should handle `handle_unknown="ignore"` as well as `drop="if_binary"`.

ENH specify categories and use drop=if_binary

---

.github/workflows/deploy-gh-pages.yml
build_tools/circle/build_jupyter_book.sh

nbformat 5.1 adds random ids to cells which creates issues with jupyter-cache.
This manifests itself as cell outputs not being shown (e.g. `df.head()` output is blank below):
Warnings like:
```
WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
WARNING: Couldn't find cache key for notebook file python_scripts/02_numerical_pipeline_ex_01.py. Outputs will not be inserted.
```
Thanks @Phaide for noticing!
This problem is mentioned here for example: https://github.com/mwouts/jupytext/issues/715

Pin nbformat to 5.0.8 to avoid regression.

---

environment.yml
requirements.txt

sphinxcontrib-bibtext problem has likely been fixed (originally a problem in 2.0.0 released in December 2020, many releases since).
imblearn does not exist in conda-forge, its name is imbalanced-learn. Use the same name for pip.

Tweak requirement files.

---

.github/workflows/deploy-gh-pages.yml
build_tools/circle/build_jupyter_book.sh

Fixed in https://github.com/executablebooks/jupyter-cache/pull/62 and 0.4.2 jupyter-cache release.
Reverts #155.

Unpin nbformat now after jupyter-cache 0.4.2 release.

---

.circleci/config.yml
build_tools/circle/checksum_python_files.sh

CircleCI only supports hashing a single file for the cache key. The `jupyter-cache` cache depends on all the `python_scripts` file so we use a script that creates a single file with the hashes of all the `python_scripts` files.
Idea was taken from:
- https://medium.com/@chrisbanes/circleci-cache-key-over-many-files-c9e07f4d471a
- https://github.com/chrisbanes/tivi/commit/c1219aeee9f62600fcd43d7caf1ea21e6e92930f

Use CircleCI cache for jupyter-cache folder.

---

python_scripts/02_numerical_pipeline_hands_on.py
python_scripts/02_numerical_pipeline_scaling.py
python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/cross_validation_train_test.py
python_scripts/ensemble_gradient_boosting.py
python_scripts/ensemble_hist_gradient_boosting.py
python_scripts/ensemble_hyperparameters.py
python_scripts/ensemble_introduction.py
python_scripts/ensemble_random_forest.py
python_scripts/linear_models_ex_03.py
python_scripts/linear_models_regularization.py
python_scripts/linear_models_sol_03.py
python_scripts/linear_regression_non_linear_link.py
python_scripts/parameter_tuning_automated.py
python_scripts/parameter_tuning_manual.py

closes #194
Use cross-validation whenever possible instead of a single train-test split.
When this is not possible (for the sake of clarity or computation time), I added a disclaimer.
We should make an additional pass on the example to see if we should sometimes add an additional disclaimer as well.

use cross-validation instead of single split

---

python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_01.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/parameter_tuning_automated.py
python_scripts/parameter_tuning_ex_02.py
python_scripts/parameter_tuning_ex_03.py
python_scripts/parameter_tuning_sol_02.py
python_scripts/parameter_tuning_sol_03.py

closes #74 
Use `handle_unknown` to show how to deal with rare categories.

use handle_unknown in OrdinalEncoder and OneHotEncoder

---

python_scripts/02_numerical_pipeline_sol_01.py

after the train_test_split section, the word "class" is written twice in a sentence.
sentence: We will first create a dummy classifier

Delete duplicate written word: "class"

---

python_scripts/parameter_tuning_ex_03.py
python_scripts/parameter_tuning_randomized_search.py
python_scripts/parameter_tuning_sol_03.py

loguniform has been added in scipy 1.14 (released December 2019)
log-uniform is easier to grasp (and remember) than reciprocal also this avoids mentioning both names.

Use loguniform rather than reciprocal.

---

python_scripts/ensemble_bagging.py

/cc @glemaitre 
In particular this removes the swarmplot / pd.melt usage and instead uses a scatter plot with blue circle to more intuitively illustrate bootstrap resampling.
It also add bagged polynomial regression pipeline in the end.

Reworked bootstrapping notebook

---

notebooks/parameter_tuning_randomized_search.ipynb
python_scripts/parameter_tuning_randomized_search.py

This PR changes 2 things:
- first, only use the inner parallelism of HistGradientBoosting instead of process level parallism with `n_jobs=4` in the `RandomizedSearchCV` call itself. I noticed it caused oversubsubscription performance problems with our current configuration of `OMP_NUM_THREADS` and the jupyterhub docker spawner config
- secondly, be more explicit about how to analyze the plot.
The second point is based on the feedback of:
https://mooc-forums.inria.fr/moocsl/t/video-to-explain-how-to-use-the-interactive-parallel-coordinates-plot/2548
I know this is kind of partially answering the quiz but I think it is fine. The goal of the quiz is check that the student carefully read and understood the analysis and could reproduce it and refine it further.
I think having a video to redo …

Improve randomized search cv notebook

---

jupyter-book/_config.yml

I am not sure about the indentation level.
Source:
https://jupyterbook.org/interactive/interactive.html#plotly
Original report:
https://mooc-forums.inria.fr/moocsl/t/missing-figure-in-the-solution-of-ex-m3-02/2896/2

Try to render plotly figures in the jupyterbook

---

environment-dev.yml
requirements-dev.txt

0.11 is a breaking change that changes the format of _toc.yml see https://github.com/executablebooks/jupyter-book/blob/master/CHANGELOG.md#v0111.

Pin jupyter-book to 0.10.2.

---

python_scripts/02_numerical_pipeline_scaling.py

The idea is to emphasize that using a simple train/test split is not wrong, but could be improved.

Improve single split wording

---

python_scripts/linear_models_regularization.py
python_scripts/logistic_regression_non_linear.py
python_scripts/parameter_tuning_randomized_search.py

Possible typos at line 300?
an -> and?
closed -> close?
https://github.com/inria/scikit-learn-mooc/blob/0074787609e1ec761f84c64ba5f3ba3a64a9553e/python_scripts/linear_models_regularization.py#L300

Typos in linear_models_regularization.py?

---

python_scripts/parameter_tuning_grid_search.py

Fix #351 (inconsistency between hand-rolled parameter tuning and grid search)

Make parameter grid consistent between exercise and notebook

---

python_scripts/parameter_tuning_grid_search.py

Made several changes to address Issue #376, i.e., to give a clear reminder of the use of `OrdinalEncoder` and `OneHotEncoder`.
Fixed some typos, grammar and markdown.

Fix wording on grid-search parameter tuning

---

jupyter-book/index.md

Fix #335.
This is the simplest thing I found to add the table of contents.
- the `tableofcontents` JupyterBook directive only shows the table of contents of the current document so it needs to be in `index.md`
- Using the class `remove-from-content-only` so that this is not shown in FUN
- I tried different variations using a markdown heading but got a JupyterBook warning "WARNING: Header nested in this element can lead to unexpected outcomes" and it was not working as expected so I used some HTML directly
We could make it prettier with some CSS (for example make the module titles more visible) but let's leave this for another day.

Add JupyterBook table of contents

---

jupyter-book/_toc.yml
jupyter-book/appendix/notebook_timings.md
jupyter-book/appendix/toc_redirect.md
jupyter-book/index.md
jupyter-book/toc.md

- appendix/toc_redirect with an HTML redirect was the simplest way I found to add a link to the left hand side panel that goes to the table of contents. Otherwise the toc is accessible as `/toc.html`
- also add notebook timings to _toc.yml
The main thing is that the root document in `_toc.yml` (so `toc` in this PR, previously `index`) needs to be the place where the `tableofcontents` directive is used since this directive only show the table of contents for the current document.

Put table of contents outside of index.md

---

jupyter-book/appendix/glossary.md
jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md
jupyter-book/tuning/parameter_tuning_module_intro.md
python_scripts/02_numerical_pipeline_introduction.py
python_scripts/datasets_bike_rides.py
python_scripts/datasets_california_housing.py
python_scripts/logistic_regression.py
python_scripts/metrics_regression.py

Fix "a/an before h" rule (see [here](https://www.gramlee.com/blog/indefinite-articles-a-or-an-before-h-blame-the-confusion-on-the-french/) for example):
> However, words that start with the letter “H” do not follow the rule for consonants. For the letter “H”, the pronunciation dictates the indefinite article:
> 
>     Use “a” before words where you pronounce the letter “H” such as “a hat,” “a house” or “a happy cat.”
>     Use “an” before words where you don’t pronounce the letter “H” such as “an herb,” “an hour,” or “an honorable man.”

Fix a/an before h

---

python_scripts/02_numerical_pipeline_scaling.py

closes #446 
Adds code to visualize the effect of `StandardScaler` on gaussian blobs created with `sklearn.datasets.make_blobs`

Add illustration of the effect of scaling data

---

jupyter-book/ensemble/ensemble_wrap_up_quiz.md
notebooks/03_categorical_pipeline_column_transformer.ipynb
notebooks/03_categorical_pipeline_ex_02.ipynb
notebooks/03_categorical_pipeline_sol_02.ipynb
notebooks/ensemble_hist_gradient_boosting.ipynb
notebooks/ensemble_sol_05.ipynb
notebooks/parameter_tuning_ex_02.ipynb
notebooks/parameter_tuning_grid_search.ipynb
notebooks/parameter_tuning_nested.ipynb
notebooks/parameter_tuning_randomized_search.ipynb
notebooks/parameter_tuning_sol_02.ipynb
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/ensemble_hist_gradient_boosting.py
python_scripts/ensemble_sol_05.py
python_scripts/parameter_tuning_ex_02.py
python_scripts/parameter_tuning_grid_search.py
python_scripts/parameter_tuning_nested.py
python_scripts/parameter_tuning_randomized_search.py
python_scripts/parameter_tuning_sol_02.py

Fixes #475. Removes `enable_hist_gradient_boosting` since this import is no longer necessary for scikit-learn >= 1.
I am making the corresponding MR in gitlab for the quiz.

MNT Remove `enable_hist_gradient_boosting`

---

notebooks/metrics_classification.ipynb
python_scripts/metrics_classification.py

Fixes #481. We were getting some deprecation warnings with scikit-learn >= 1 when using `plot_confusion_matrix`, `plot_precision_recall_curve` and `plot_roc_curve`.

Replace plot_* function by Display in metrics_classification.py

---

python_scripts/03_categorical_pipeline_column_transformer.py

Wrap-up M1 Q4 has a score of 61.4% This shows that dates can easily be confused with an ordinal category. 
This PR adds an explanation on how date and age are related.

Add explanation of dates relation to age

---

jupyter-book/appendix/glossary.md
python_scripts/ensemble_bagging.py
python_scripts/ensemble_gradient_boosting.py
python_scripts/ensemble_sol_02.py
python_scripts/trees_ex_02.py
python_scripts/trees_hyperparameters.py
python_scripts/trees_regression.py
python_scripts/trees_sol_02.py

closes #442 
In some notebooks the word "test" is used for denoting data generated in equally-spaced intervals for the visual evaluation of the
predictions, given that such data was not seen during training. This could be confusing with the notion of "test" as a subset of the data coming from either a train-test split or cross-validation.
I changed  `data_test` to `data_range` whenever the former meaning was intended. The notation was chosen to match with [this notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_sol_02.html), where we use the term `data_ranges` instead of `data_test`. I also edited the rest of the text accordingly and added a warning when _both_ meanings were intended in the same notebook.

Clarify the notation "data_test" when no train-test split is involved

---

python_scripts/datasets_bike_rides.py
python_scripts/ensemble_bagging.py
python_scripts/linear_models_regularization.py

The reason is that we will still have some remaining warnings that are not addressed in #484.
- The `UserWarning` in [ensemble_bagging](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_bagging.html) could be fixed by addressing [#21599](https://github.com/scikit-learn/scikit-learn/issues/21599). In this PR I simply use a `warnings.filterwarnings`.
- The `UserWarning` in [ensemble_sol_02](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_sol_02.html) may be fixed by [#21578](https://github.com/scikit-learn/scikit-learn/pull/21578).
- The `FutureWarning` in [datasets_bike_rides](https://inria.github.io/scikit-learn-mooc/python_scripts/datasets_bike_rides.html) is fixed by updating `datetimelike` index notation.
- The `SettingWithCopyWarning` in …

MNT Fix or explain remaining warnings

---

python_scripts/ensemble_ex_02.py
python_scripts/ensemble_sol_02.py
python_scripts/linear_regression_in_sklearn.py
python_scripts/linear_regression_without_sklearn.py
python_scripts/trees_dataset.py
python_scripts/trees_ex_02.py
python_scripts/trees_regression.py
python_scripts/trees_sol_02.py

The [first exercise on linear models](linear_models_sol_01.py) uses the notation in singular `feature_name = "Flipper Length (mm)"` but some other notebooks define the variable in plural (i.e. `feature_names = "Flipper Length (mm)"`) even if there is one feature only. This PR solves this small detail and looks for consistency in notation across these notebooks.

MNT Improve consistency of definitions

---

jupyter-book/_toc.yml
jupyter-book/predictive_modeling_pipeline/03_categorical_pipeline_video.md
python_scripts/video_pipeline.py

Fixes #465.
I think the best place for the video would be somewhere between [Exercise M1.05](https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline_sol_02.html) and the first wrap-up quiz.
The idea is that the video and notebook will be displayed simultaneously within a split webpage. This may require FUN changes.

ENH Add python code for notebook used in the `Pipeline` video

---

python_scripts/cross_validation_grouping.py

We have a small discrepancy between the number of writers identified in the target and the one provided by the documentation. However, we are able to show the effect of the groups. So we provide a small discussion just to avoid surprises.

Improve group identification in digits example

---

python_scripts/linear_models_regularization.py

Partially address #276 by removing "dispersion" and using "scale" for this specific case.

Use scale instead of dispersion

---

python_scripts/linear_models_sol_04.py

closes #276 
Introduce the parameter `drop` from the `OneHotEncoder` through the exercise presenting the problem of collinear features.

Add information regarding the drop option in the linear model exercise

---

python_scripts/ensemble_bagging.py
python_scripts/ensemble_gradient_boosting.py
python_scripts/ensemble_sol_02.py
python_scripts/trees_hyperparameters.py
python_scripts/trees_regression.py
python_scripts/trees_sol_02.py

We were using:
```py
plt.plot(dataframe_single_column, array_1d)
```
This is probably edge-casy and breaks with pandas 1.4 (released a few days ago). Whether this is a regression at the interface between pandas and matploblib is debatable. We need to fix it anyway in this repo even if it eventually gets fixed in matplotlib or pandas.
I suspect this happened by coincidence, before we were using numpy arrays, and we introduced dataframes to make scikit-learn happy about having feature names at predict time. The code was working fine until it didn't ...

Fix for pandas 1.4

---

jupyter-book/predictive_modeling_pipeline/03_categorical_pipeline_video.md
jupyter-book/tuning/parameter_tuning_parallel_plot_video.md

The titles of the credits for the pipeline and parallel plot videos were corrected for consistency with the course titles.
These 2 videos have different links on YouTube (you can't correct/replace a video on YouTube, you have to delete the old one and reload the new one). Therefore, this PR updates the url and ensures consistency with #532 .

Update title in YouTube videos

---

python_scripts/02_numerical_pipeline_ex_00.py
python_scripts/02_numerical_pipeline_sol_00.py

In the [Solution for Exercise M1.02](https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_sol_00.html) we present how to access the description of a model using, for instance, the syntax `KNeighborsClassifier?` in this particular case.
I think the description could be improved, as it may not be clear for beginners that the `?` character was not a typo, but part of code we expected them to try.

Improve description on how to access help inside notebook

---

python_scripts/cross_validation_baseline.py
python_scripts/cross_validation_ex_02.py
python_scripts/cross_validation_grouping.py
python_scripts/cross_validation_sol_02.py
python_scripts/cross_validation_train_test.py
python_scripts/cross_validation_validation_curve.py
python_scripts/datasets_ames_housing.py
python_scripts/datasets_bike_rides.py
python_scripts/datasets_blood_transfusion.py
python_scripts/logistic_regression.py

Partially addresses #539.
This PR removes the `density=True` argument when comparing baselines in M7 as suggested in [this forum comment](https://mooc-forums.inria.fr/moocsl/t/density-argument-in-plt-hist/4191/2).
It also introduces a brief explanation the first time this argument appears.
Side effect: removes an unnecessary (blank) solution cell.

Explain density argument in plt.hist

---

python_scripts/linear_models_ex_04.py
python_scripts/linear_models_sol_04.py

I saw that first (weird multiple "write your code here" cells) in https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_ex_04.html:
and ended up improving the motivations of the exercise additional correction section

Improve motivation of OneHotEncoder drop parameters

---

python_scripts/02_numerical_pipeline_hands_on.py
python_scripts/02_numerical_pipeline_introduction.py
python_scripts/video_pipeline.py

Partially addresses #530.
This PR adds comments on the `score` method in the M1: 
- the first time the method is used
- the first time we use a test set for scoring
- in the pipeline video, where care has to be taken on interpreting the result naively

Sprinkle M1 with comments on what the evaluation means

---

jupyter-book/_toc.yml
jupyter-book/concluding_remarks_video.md

We discussed the possibility of having the video in the same page as the [concluding remarks](https://inria.github.io/scikit-learn-mooc/concluding_remarks.html), but we also mentioned that we should keep a similar format as in FUN, where we placed the video in its own page. This PR does the latter, as this may also help avoiding a very charged and long page.

Add concluding remarks video

---

python_scripts/parameter_tuning_randomized_search.py

Somewhat related to  #304. In the [randomized search notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_randomized_search.html) we still use a notion of "substantially better" based on comparing the difference of the mean test scores of two models w.r.t. the standard deviation of said scores.
Furthermore, in this case the difference depends on the `random_state` as mentioned in [this forum post](https://mooc-forums.inria.fr/moocsl/t/no-significance-between-the-2-best-models/7689/2). Therefore, the conclusions drawn are not true and are in contradiction with the following paragraph: 
> In fact, there might be other sets of parameters leading to similar or better generalization performances but that were not tested in the search.
This PR simply removes this …

Remove interpretation of scores that depends on `random_state`

---

python_scripts/01_tabular_data_exploration_ex_01.py
python_scripts/02_numerical_pipeline_ex_00.py
python_scripts/02_numerical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/cross_validation_ex_01.py
python_scripts/cross_validation_ex_02.py
python_scripts/ensemble_ex_01.py
python_scripts/ensemble_ex_02.py
python_scripts/ensemble_ex_03.py
python_scripts/ensemble_ex_04.py
python_scripts/feature_selection_ex_01.py
python_scripts/linear_models_ex_01.py
python_scripts/linear_models_ex_02.py
python_scripts/linear_models_ex_03.py
python_scripts/linear_models_ex_04.py
python_scripts/linear_models_ex_05.py
python_scripts/metrics_ex_01.py
python_scripts/metrics_ex_02.py
python_scripts/parameter_tuning_ex_02.py
python_scripts/parameter_tuning_ex_03.py
python_scripts/trees_ex_01.py
python_scripts/trees_ex_02.py

Follow-up of #579.
This puts back exercises as generated by `make exercises`.
I looked a bit in the jupytext code, but there is no straightforward way to remove the jupytext header, see https://github.com/INRIA/scikit-learn-mooc/pull/408#issuecomment-1041463684.
I assume it's the same thing for the `utf-8 first line`. Note that the reason that `utf-8` appeared in the rendering was that they were after the yaml frontmatter due to #576 adding frontmatter at the top where there was none. Having them in the first line (or at least before the front matter) will not cause them to show up in the rendered HTML or notebook.
We could get rid of jupytext info in the frontmatter by hand if we really wanted to, there is an old TODO about this in …

Regenerate exercises with make exercises

---

environment-dev.yml
environment.yml
requirements-dev.txt
requirements.txt

This is to avoid https://github.com/ipython/ipython/issues/12467#issuecomment-1031486805.
This affects the MOOC since errors inside `joblib.Parallel` with `n_jobs > 1` looks like cells than runs forever without any output e.g. https://mooc-forums.inria.fr/moocsl/t/q7-taking-too-long-to-run-validation-curve-on-data/8023/8

Use IPython 7 as a temporary work-around

---

notebooks/02_numerical_pipeline_hands_on.ipynb
python_scripts/02_numerical_pipeline_hands_on.py

https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_hands_on.html
The only place this is used is here:
I think it is fine to start using HTML diagrams in the next notebook where at least there is a pipeline.
If we want to keep it, we may put the `set_config` code somewhere else (e.g. at the beginning of the notebook) since with the sentence before it looks like this is part of creating the `LogisticRegression`

Remove not super useful set_config diagram

---

python_scripts/cross_validation_learning_curve.py

Hi,
Quick fix for a typo. Also, I had to Google [Bayes error rate](https://en.wikipedia.org/wiki/Bayes_error_rate) after reading this paragraph, but I couldn't find a link in the notebook for that. Are there any plans to have footnotes (like in GitHub Markdown [^1]) with useful links? Or maybe these links are in the forum or somewhere else?
Thanks!
[^1]: for example

Fix typo s/might have reach/might have reached

---

.github/workflows/deploy-gh-pages.yml

The Github Action build is failing because scikit-learn 1.1 needs Python 3.8, see 
https://github.com/INRIA/scikit-learn-mooc/runs/6861980012?check_suite_focus=true with the error:
```
ERROR: No matching distribution found for scikit-learn>=1.1.1
```
I used Python 3.9 to have the same version as the Circle build.
Reminder:
- right now Circle is used for PRs (and be able to see the rendered HTML of the PR)
- Github Action is used to build from main and push the website to github-pages

MNT bump Python version to be compatible with scikit-learn 1.1

---

check_env.py
environment-dev.yml
environment.yml
local-install-instructions.md

Calling plotly on versions < v5.9.0 was raising a [FutureWarning](https://github.com/plotly/plotly.py/issues/3602) about pandas `DataFrame.append` method being deprecated (see for instance https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_parallel_plot.html).
This PR updates plotly to the latest version to avoid such issue.

Update plotly version

---

python_scripts/ensemble_adaboost.py
python_scripts/ensemble_bagging.py
python_scripts/ensemble_ex_01.py
python_scripts/ensemble_introduction.py
python_scripts/ensemble_random_forest.py
python_scripts/ensemble_sol_01.py
python_scripts/logistic_regression.py

This PR solves two different `FutureWarning` being raised in v1.2:
FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
FutureWarning: `penalty='none'` has been deprecated in 1.2 and will be removed in 1.4.

MAINT Fix FutureWarnings for v1.2

---

check_env.py
environment-dev.yml
environment.yml
local-install-instructions.md
requirements-dev.txt
requirements.txt

The sickit-learn v1.1.1 was introduced in #637.
Now the time has come to update to v1.2.1.
This is required for #674 and #683.

MAINT Update scikit-learn to v 1.2.1

---

notebooks/03_categorical_pipeline.ipynb
notebooks/03_categorical_pipeline_ex_02.ipynb
notebooks/03_categorical_pipeline_sol_02.ipynb
notebooks/linear_models_sol_04.ipynb
python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/linear_models_sol_04.py

`OneHotEncoder.sparse` is deprecated in favor of `OneHotEncoder.sparse_output`

FIX use sparse_output parameter for OneHotEncoder

---

python_scripts/metrics_classification.py

Since 1.3 we can use the `plot_chance_level` parameter for ROC and PR curves. I propose mentioning it at the end of the [Classification notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/metrics_classification.html), so that we introduce the concept of chance level using a `DummyClassifier` before showing this feature.

Introduce use of plot_chance_level parameter

---

requirements-dev.txt

Deploy a partial fix for https://github.com/executablebooks/sphinx-book-theme/issues/541.
See discussion there for the details on what's missing.

Make the navbar scroll to the current page header

---

python_scripts/linear_models_ex_03.py
python_scripts/linear_models_sol_03.py
python_scripts/linear_regression_non_linear_link.py

Fixes #358.
The [Exercise M4.03](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_sol_03.html) is part of the non-linear features section but currently it does not mention anything related to such subject. As proposed by @ogrisel, this PR introduces non-linear feature engineering in more than 1D.
I had to get rid of the boxplot mentioning the stability of the coefficients because they are not on the same scale. I can add a standard scaler step, but may make the exercise too complex.

Introduce non-linear feature engineering in more than 1D

---

python_scripts/ensemble_hyperparameters.py

Fixes #448.
This PR reworks the [Hyperparameter tuning for ensemble methods notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_hyperparameters.html) to:
- replace GBDT by HGBT (and adapt discussion)
- add wrap-up table
- prefer verbs in present mode

Replace GBDT by HGBT and add wrap-up table

---

check_env.py
environment-dev.yml
environment.yml
local-install-instructions.md
requirements-dev.txt
requirements.txt

PR #702 introduced `ValidationCruveDisplay` which requires v >= 1.3. This PR updates the requirements and, as a side effect, formats the code on those files.

MAINT Update scikit-learn to v 1.3

---

python_scripts/cross_validation_validation_curve.py

Follows #702. See also [#27311](https://github.com/scikit-learn/scikit-learn/pull/27311).
Passing a list to the `param_range` parameter in `ValidationCurveDisplay` may rise a hard to debug
```python-traceback
AttributeError: 'list' object has no attribute 'min'
```
if the spacing in the grid looks appropriate to use a "symlog" according to the current logic in the private function `_interval_max_min_ratio`.
I think that should be fixed in scikit-learn, but for the moment enforcing consistently passing numpy arrays may be a good fix.

Always pass a numpy array to ValidationCurveDisplay's `param_range`

---

jupyter-book/appendix/glossary.md
python_scripts/02_numerical_pipeline_introduction.py
python_scripts/02_numerical_pipeline_scaling.py
python_scripts/cross_validation_validation_curve.py
python_scripts/ensemble_bagging.py
python_scripts/parameter_tuning_manual.py

Fixes #427.
Instead of introducing links, I added a phrase encouraging the use of the glossary and short definitions of:
- API
- estimator
- predictor
- transformer
- hyperparameter
Side effect: Prefer use of verbs in present mode.

ENH Add explicit definitions for technical terms

---

python_scripts/linear_models_ex_02.py
python_scripts/linear_models_sol_02.py
python_scripts/linear_regression_non_linear_link.py

Addresses suggestions in [this commment](https://github.com/INRIA/scikit-learn-mooc/pull/696#discussion_r1309981324) by @ogrisel.
Side effects:
- adds reminder on reverting the sign in "neg_mean_absolute_error";
- fixes reference "in the following notebook" which is no longer true after the reordering;
- changes the behavior of Nystroem on the [Linear regression for a non-linear features-target relationship notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_regression_non_linear_link.html) to use a polynomial kernel, as it seems more pertinent to the contents of the notebook.

ENH Expand contents related to Nystroem

---

jupyter-book/ensemble/ensemble_wrap_up_quiz.md
jupyter-book/overfit/overfit_wrap_up_quiz.md

Follows #712. See also #702.
Passing a list to the `param_range` in `ValidationCurveDisplay` may rise an `AttributeError`. Even if scikit-learn 1.3.1 will support lists for `param_range`, it is better to enforce consistently passing numpy arrays to validation curves.
Side effect: We revisited the interval suggested for `max_iters`.

Synchronize quizzes to use ValidationCurveDisplay

---

python_scripts/trees_classification.py
python_scripts/trees_regression.py
python_scripts/trees_sol_01.py

This PR solves
```python-traceback
InvalidParameterError: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got ... instead.
```

Fix InvalidParameterError in plot_tree

---

python_scripts/logistic_regression.py

Follows #715.
This PR reuses the pedagogical introduction of the `predict_proba` concept done in the [Classification tree notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/trees_classification.html), which may make such notebook relatively redundant. We may consider revisiting its contents.

ENH Expand contents related to pedict_proba

---

environment-dev.yml
environment.yml
local-install-instructions.md
requirements-dev.txt
requirements.txt

The version of pandas 2.1 is conflicting with seaborn. This is a quick fix until the issue is addressed on their side.
I did not modify check_env.py to keep the minimal required version of pandas to 1.0

MAINT Fix pandas version to 2.0 to avoid seaborn warning

---

jupyter-book/linear_models/linear_models_quiz_m4_01.md
jupyter-book/linear_models/linear_models_quiz_m4_02.md
jupyter-book/linear_models/linear_models_quiz_m4_03.md
jupyter-book/linear_models/linear_models_quiz_m4_05.md

This PR:
- modifies Q2 in M4.01 to be more consistent with later-introduced contents;
- introduces 2 questions in M4.02 related to the content introduced in #723;
- adds question in M4.03 regarding feature engineering in general;
- modifies M4.05 to address [this comment](https://github.com/INRIA/scikit-learn-mooc/pull/710#discussion_r1340333330);
- adds a question in M4.05 regarding the underfitting-overfitting trade-off in logistic regression `C`.

Synchronize quizzes related to `predict_proba` and M4 refactoring

---

python_scripts/linear_regression_non_linear_link.py

This PR:
- changes the title for consistency with the rest of the module
- adds preamble to building custom dataset;
- removes a "note" to reduce the number of highlights;
- defines a helper function to reduce boilerplate;
- displays the pipeline after the definition of each model;
- simplifies narrative on `PolynomialFeatures`;
- addresses [this suggestion](https://github.com/INRIA/scikit-learn-mooc/pull/711#discussion_r1322648681) to add splines to the discussion.

ENH Remove boilerplate from non-linear regression notebook

---

requirements-dev.txt

The CI was running on the branch related the PR https://github.com/executablebooks/sphinx-book-theme/pull/754. When the branch was erased by the merge, the CI got broken.
This PR fixes the issue by pointing to the respective commit.

MAINT Fix broken sphinx-book-theme reference in CI

---

python_scripts/parameter_tuning_ex_02.py
python_scripts/parameter_tuning_grid_search.py
python_scripts/parameter_tuning_nested.py
python_scripts/parameter_tuning_randomized_search.py
python_scripts/parameter_tuning_sol_02.py

Fixes #476.
The fact that `HistGradientBoostingClassifier` does not support sparse data is not a problem when used along with `OrdinalEncoder` inside a pipelines. This PR simplifies the code by removing the `sparse_threshold=0` parameter from the `ColumnTransformer`.

MAINT Remove sparse_threshold

---

python_scripts/linear_models_feature_engineering_classification.py

Follows #711.
In the M4 wrap-up quiz we ask students to use splines instead of standard scaling.
This PR sets a bit of context on why that can be done.
Side effect: A bit of wording of the previous content.

ENH Mention scaling behavior of binning and splines

---

environment-dev.yml
environment.yml
local-install-instructions.md
requirements-dev.txt
requirements.txt

As mentioned in https://github.com/INRIA/scikit-learn-mooc/pull/727#issuecomment-1776912757, the `FutureWarning` being raised by seaborn was fixed in v0.13.
This PR unpins the pandas version and updates the seaborn version instead.

MAINT Revert fix pandas version

---

jupyter-book/trees/trees_wrap_up_quiz.md

@lfarhi noticed a degrade of the performance of the tree model at the end of wrap-up quiz M5. The reason is that Pandas>2.0 converts `None` into `NaN`, which broke the pipeline with ordinal encoding. This PR fixes the issue.

MAINT Update wrap-up quiz M5

---

python_scripts/parameter_tuning_nested.py

Fixing the typo reported in:
https://mooc-forums.inria.fr/moocsl/t/suspected-typo/15589

FIX fix description to be aligned with figure legend

---

notebooks/metrics_classification.ipynb
python_scripts/metrics_classification.py

The recall formula wasn't rendering properly.

Fix formatting

---

python_scripts/cross_validation_stratification.py

Fix typo in cross_validation_stratification.py

---

python_scripts/01_tabular_data_exploration.py
python_scripts/02_numerical_pipeline_hands_on.py
python_scripts/02_numerical_pipeline_introduction.py
python_scripts/03_categorical_pipeline.py
python_scripts/03_categorical_pipeline_column_transformer.py
python_scripts/cross_validation_train_test.py
python_scripts/linear_models_ex_02.py
python_scripts/linear_models_sol_02.py
python_scripts/linear_regression_without_sklearn.py
python_scripts/parameter_tuning_grid_search.py
python_scripts/parameter_tuning_manual.py
python_scripts/parameter_tuning_randomized_search.py
python_scripts/trees_dataset.py

As suggested by @ogrisel in RL, this PR removes the `head` method from most of the notebooks when displaying the info of a dataframe. This results in a more vertical notebook but also provides more information in a glance, e.g. the shape of said dataframe.

MAINT Remove head method

---

python_scripts/02_numerical_pipeline_introduction.py
python_scripts/03_categorical_pipeline.py
python_scripts/cross_validation_train_test.py
python_scripts/ensemble_sol_02.py
python_scripts/linear_models_ex_04.py
python_scripts/linear_models_sol_04.py
python_scripts/metrics_regression.py

As per RL feedback from @tuscland, in this PR:
- corrects a typo "metioned" -> "mentioned";
- changes idiomatic expression "to linger on" -> "to focus on";
- adds a comment on overfitting when random forest are not correctly tuned;
- adds link towards wikipedia to explain the concept of "expected value" as a generalization of the weighted average.

MAINT Fix typos and wording across the mooc

---

python_scripts/cross_validation_stratification.py

During a formation at Inria Academy we noticed that this notebook never really justifies why stratification is important. This PR adds a couple of paragraphs to better motivate the reason why a simple `KFold` with shuffling is not a good enough practice.
It also takes the opportunity to implement verbs in present mode and improve general wording.
NB. I think this PR is safe to merge at it does not change the overall experience of the mooc.

ENH Improve wording in stratification notebook

---

python_scripts/ensemble_gradient_boosting.py

Originally I wanted to rework only the wording, as well explaining the GBDT algo is the cornerstone for understanding HGBT. But then I decided to factorize the code by introducing a helper function to keep the focus on the narrative other than the code.

ENH Rework narrative of GBDT notebook

---

python_scripts/cross_validation_grouping.py

This PR improves the motivation for group-aware cross-validation techniques, revisits the general wording and changes the number of bins in the plots to better reflect the distributions.
Note: A recurrent question in live sessions is why not using the writers' ids as a feature. This is also addressed here.

ENH Improve wording in group-aware cross-validation notebook

---

python_scripts/01_tabular_data_exploration.py
python_scripts/cross_validation_learning_curve.py
python_scripts/linear_models_feature_engineering_classification.py
python_scripts/logistic_regression.py
python_scripts/metrics_classification.py
python_scripts/parameter_tuning_sol_03.py

1. At the end of the [First look at the dataset notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration.html), under the heading "we made important observations" we mention that linear models can only capture linear interactions but there is no prior reference to linear models.
2. The word "complex" at the end of the [Effect of the sample size in cross-validation notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/cross_validation_learning_curve.html) may be misleading. Here we don’t mean complexity as in the depth of a decision tree or the degree of a polynomial (which indeed would lead to overfitting), but rather that a more "expressive" model should be used.
3. In the [Solution for Exercise …

FIX Several small fixes

---

.github/workflows/deploy-gh-pages.yml
.github/workflows/jupyter-book-pr-preview.yml

download-artifact v4 supports downloading artifact from workflow run-id.
Closes https://github.com/INRIA/scikit-learn-mooc/pull/782 dependabot PR that was suggesting to update the `dawidd6/action-download-artifact` for security reasons.
Also artifact v3 is going to stop being supported end of January 2025 see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.
I am trying to do some basic testing in my fork in https://github.com/lesteve/scikit-learn-mooc/pull/2 prior to merging.

CI Use actions upload-artifact and download-artifact v4 

---

check_env.py
environment-dev.yml
environment.yml
local-install-instructions.md
requirements-dev.txt
requirements.txt

MAINT Update scikit-learn to v 1.6

---

notebooks/ensemble_ex_03.ipynb
notebooks/ensemble_sol_03.ipynb
python_scripts/ensemble_ex_03.py
python_scripts/ensemble_sol_03.py

Fixes #793
I updated the text regarding the number of trees in a GBDT model.

update explanation on nr of trees in GBDT

---

python_scripts/cross_validation_time.py

Fixes #786. This PR:
- Complements on the description;
- Corrects the render of the plots by ordering the index;
- Corrects a warning being raised by using `groups` with `TimeSeriesSplit`;
- Introduces a clearer explanation on why the cross-validation with shuffle is not adequate for time series.

Rework cross_validation_time.py

---

jupyter-book/_static/sklearn_mooc.js

It seems like the Binder link is opening a `.py` file and not a notebook. See [page](https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration.html) and [Binder link](
https://mybinder.org/v2/gh/INRIA/scikit-learn-mooc/main?urlpath=tree/python_scripts/01_tabular_data_exploration.py). It used to work a while ago because with the legacy notebook interface, jupytext was opening the `.py` as a notebook.
Now that Binder is supposed to be more stable, maybe it is worth fixing.
Close https://github.com/INRIA/scikit-learn-mooc/issues/190.
This seems to work, see [this page](https://pull-request-807--scikit-learn-mooc.netlify.app/python_scripts/01_tabular_data_exploration) in the rendered doc.
This seems a bit hacky but I did not find anything cleaner unfortunately ...

MNT Fix Binder link

---

python_scripts/cross_validation_time.py

The last sentence of the `cross_validation_time.ipynb` notebook felt a bit convoluted. I tried my best to improve the formulation.

better formulation to wrap-up

---

jupyter-book/_config.yml
jupyter-book/_static/sklearn_mooc.css
jupyter-book/concluding_remarks.md

Now that the official scikit-learn certification has been launched, more and more people will use the mooc as a reference to prepare themselves. It would then make sense if the certification points to the mooc and vice-versa, to improve legitimacy.

Add info about the certification

---

python_scripts/ensemble_bagging.py
python_scripts/linear_models_feature_engineering_classification.py

Hey team! Fixed errors:
python_scripts/linear_models_feature_engineering_classification.py
`bootstraping` - `bootstrapping`
python_scripts/linear_models_feature_engineering_classification.py
`orignal` - `original`

minor docstring fixups

---

notebooks/parameter_tuning_grid_search.ipynb
python_scripts/parameter_tuning_grid_search.py

Fixed the time issue @ArturoAmorQ created by #847 .

MTN Hyperparameter tuning with grid search

---

jupyter-book/appendix/glossary.md

Linked to PR #856, added an entry to the glossary about model states.

MTN Added model state to the glossary

---

python_scripts/02_numerical_pipeline_scaling.py

Following this [excellent remark](https://mooc-forums.inria.fr/moocsl/t/a-quick-feedback-about-the-introduction-of-iterations/15934), gave a quick explanation of why we consider the number of iterations when we introduce logistic regression and numerical optimization.

MTN Proposal for explantation of what are iterations
